-- users
insert into call_center_user (user_id, first_name, last_name) values (1, 'Red', 'Moisey');
insert into call_center_user (user_id, first_name, last_name) values (2, 'Doti', 'Jerdein');
insert into call_center_user (user_id, first_name, last_name) values (3, 'Prescott', 'Josupeit');
insert into call_center_user (user_id, first_name, last_name) values (4, 'Sunshine', 'Lummasana');
insert into call_center_user (user_id, first_name, last_name) values (5, 'Shanie', 'Puddle');
insert into call_center_user (user_id, first_name, last_name) values (6, 'Estrellita', 'Mourbey');
insert into call_center_user (user_id, first_name, last_name) values (7, 'Lisetta', 'Bielfeldt');
insert into call_center_user (user_id, first_name, last_name) values (8, 'Ninetta', 'Engel');
insert into call_center_user (user_id, first_name, last_name) values (9, 'Loraine', 'Mc Meekin');
insert into call_center_user (user_id, first_name, last_name) values (10, 'Cherish', 'Hanes');
insert into call_center_user (user_id, first_name, last_name) values (11, 'Francesco', 'Iglesia');
insert into call_center_user (user_id, first_name, last_name) values (12, 'Sheri', 'Sawers');
insert into call_center_user (user_id, first_name, last_name) values (13, 'Wit', 'Chastelain');
insert into call_center_user (user_id, first_name, last_name) values (14, 'Ralf', 'Muff');
insert into call_center_user (user_id, first_name, last_name) values (15, 'Bevvy', 'D''Alwis');
insert into call_center_user (user_id, first_name, last_name) values (16, 'Nike', 'Lynett');
insert into call_center_user (user_id, first_name, last_name) values (17, 'Barney', 'Coraini');
insert into call_center_user (user_id, first_name, last_name) values (18, 'Carlos', 'Peron');
insert into call_center_user (user_id, first_name, last_name) values (19, 'Eldin', 'Mant');
insert into call_center_user (user_id, first_name, last_name) values (20, 'Craggie', 'Dubber');
insert into call_center_user (user_id, first_name, last_name) values (21, 'Jaymee', 'Sam');
insert into call_center_user (user_id, first_name, last_name) values (22, 'Torre', 'Frier');
insert into call_center_user (user_id, first_name, last_name) values (23, 'Shir', 'Hallford');
insert into call_center_user (user_id, first_name, last_name) values (24, 'Pebrook', 'Hubbold');
insert into call_center_user (user_id, first_name, last_name) values (25, 'Lia', 'Flagg');

-- calls
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (1, 'quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', false, 119.68, 1);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (2, 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', true, 42.53, 2);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (3, 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', true, 99.57, 3);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (4, 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', false, 65.1, 4);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (5, 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt', true, 67.26, 5);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (6, 'massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam', true, 26.87, 6);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (7, 'odio in hac habitasse platea dictumst maecenas ut massa quis augue', true, 35.71, 7);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (8, 'accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio', true, 78.42, 8);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (9, 'imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', true, 111.14, 9);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (10, 'sed ante vivamus tortor duis mattis egestas metus aenean fermentum', false, 70.46, 10);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (11, 'nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue', false, 118.34, 11);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (12, 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', false, 71.4, 12);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (13, 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque', true, 40.88, 13);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (14, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', true, 47.92, 14);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (15, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', false, 22.26, 15);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (16, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', true, 80.49, 16);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (17, 'volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', false, 51.04, 17);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (18, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', true, 75.78, 18);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (19, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', false, 70.7, 19);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (20, 'turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', true, 96.76, 20);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (21, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros', false, 56.51, 21);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (22, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo', false, 104.76, 22);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (23, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet', true, 106.2, 23);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (24, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', false, 74.51, 24);
insert into call_center_call (call_id, notes, is_resolved, call_time, user_id) values (25, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', true, 59.02, 25);
